RashFedProject/RashFedProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('registration/', include('registration.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('shop.urls')),
]

if (settings.DEBUG is True):
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

RashFedProject/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         cart_remove,
         name='cart_remove'),
]

RashFedProject/registration/urls.py
from django.urls import path
from .views import *

urlpatterns = [ 
    path ('', SignUp.as_view(), name="signup"),
    path ('login/', authorization, name="login"),
]

RashFedProject/shop/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name="home"),
    path('category/<int:category_id>/', product_list),
]

RashFedProject/cart/models.py
from django.db import models

# Create your models here.

RashFedProject/shop/models.py
from tabnanny import verbose
from unicodedata import category
from django.db import models

class Products(models.Model):
    name = models.CharField(max_length=50, verbose_name='Продукт')
    category = models.ForeignKey("Categories", models.PROTECT, null=True, verbose_name='Категория')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name="Фото", blank=True)

    def __str__(self):
        return self.name

    class Meta():
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ['-price']

class Categories(models.Model):
    name = models.CharField(max_length=50, verbose_name="Категория")
    subcategory = models.CharField(max_length=50, verbose_name="Подкатегория")
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name="Фото", blank=True)

    def __str__(self):
        return self.name

    class Meta():
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ['subcategory']

RashFedProject/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

RashFedProject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Products
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    cart.add(product=product)
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

RashFedProject/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Products, Categories
from cart.forms import CartAddProductForm

def index(request):
    products = Products.objects.all()
    categories = Categories.objects.all()
    return render(request, 'shop/index.html', {'products':products, 'categories':categories})

def product_list(request, category_id):
    products = Products.objects.filter(category_id=category_id)
    categories = Categories.objects.all()
    return render(request, 'shop/index.html', {'products':products, 'categories':categories})

def product_detail(request, id, slug):
    product = get_object_or_404(Products, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/index.html', {'product': product, 'cart_product_form' : cart_product_form})

RashFedProject/cart/templates/cart/detail.html
{% load static %}

{% block title %}
  <title>Корзина</title>
  <link rel="stylesheet" href="{% static 'normalize.css'%}">
  <link rel="stylesheet" href="{% static 'style2.css'%}">
{% endblock %}

{% block content %}
  <header>
    <h1>Корзина покупок</h1>
  </header>
  <table class="cart">
    <thead class="row-title">
      <tr>
        <th>Картинка</th>
        <th>Товар</th>
        <th>Обновить кол-во</th>
        <th>Удалить</th>
        <th>Кол-во</th>
        <th>Цена за шт</th>
        <th>Общая стоимость</th>
      </tr>
    </thead>
    <tbody class="row-body">
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td class="menu-root">
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.photo %}{{ product.photo.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                <input type="submit" value="добавить">
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
            <td>
              {{ item.quantity }}
            </td>
            <td class="num">₽{{ item.price }}</td>
            <td class="num">₽{{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Всего</td>
        <td colspan="4"></td>
        <td class="num">₽{{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-center">
    <a href="/" class="button light">В магазин</a>
    <a href="#" class="button">Оформить заказ</a>
  </p>
{% endblock %}

RashFedProject/shop/templates/shop/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Магазин шаурмы - RashFed</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'normalize.css'%}">
        <link rel="stylesheet" href="{% static 'style.css'%}">
    </head>
    <body>
        <header class = "header-wrapper">
                <div class="header-logo">
                    <div class="header-text">
                        <a href="/"><h1>Онлайн-магазин RashFed</h1></a>
                        <h3>Cочно! Быстро! Дёшево!</h3>
                    </div>
                </div>

                <nav class="header-menu">
                    <div class="cart">
                        {% with total_items=cart|length %}
                        {% if cart|length > 0%}
                        <h3>
                        В корзине:
                        <a href="{%url 'cart:cart_detail' %}">
                            {{total_items}} шт, ₽{{cart.get_total_price}}
                        </a>
                        </h3>
                        {% else %}
                        <h3>Корзина пустая</h3>
                        {% endif %}
                        {% endwith %}
                    </div>
                    <div class="user-profile">
                        {% if user.is_authenticated %}
                            <h1>Привет, я {{ user.username|default:'Guest' }}</h1>
                            <h3><a href="{% url 'logout' %}">Выйти из профиля</a></h3>
                    
                        {% else %}
                            <a href="/registration"><img src="../../../media/photos/2022/06/12/user-profile.png" alt="Profile"></a>
                        {% endif %}
                    </div>
                </nav>
        </header>
        <main>
            <div class="home-page-wrapper">
                <div class="home-page-menu">
                    {% for category in categories %}
                        <div class="menu-root">
                            <img src="{{ category.photo.url }}" alt="#">
                            <div class = "menu-info">
                                <a href="/category/{{category.pk}}">{{ category.name }}</a>
                                <div class = "menu-subinfo">
                                    {{ category.subcategory }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <div class="home-page-center">
                    {% for product in products %}
                        <div class="product-block">
                            <div class="product-block-image">
                                {% if product.photo %}
                                <img src="{{ product.photo.url }}" alt="PRODUCT">
                                {% endif %}
                            </div>
                            <div class="product-block-name">
                                {{ product.name }}
                                <div class="product-block-cost">
                                    {{ product.price }} ₽
                                </div>
                                <form action="{% url 'cart:cart_add' product.id %}" method="post" >
                                    {{ cart_product_form }}
                                    {% csrf_token %}
                                    <input type="submit" class="buybtn" value = "Добавить в корзину">
                                </form>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </main>
    </body>
</html>